import esbuild from "esbuild";
import { builtinModules } from "node:module";
import { watch } from "node:fs";
import { copyFile, mkdir } from "node:fs/promises";
import process from "node:process";

const mode = process.argv[2] ?? "development";
const production = mode === "production";
const diagnosticsBuild = mode === "diagnostics";
const oneShot = production || diagnosticsBuild;
const diagnosticsEnabled = !production;
const outputDirectory = ".obsidian/plugins/trail";
const staticFiles = ["manifest.json", "styles.css"];

async function copyStaticFiles() {
  await mkdir(outputDirectory, { recursive: true });

  await Promise.all(
    staticFiles.map((file) =>
      copyFile(file, `${outputDirectory}/${file}`),
    ),
  );
}

await copyStaticFiles();

const context = await esbuild.context({
  banner: {
    js: "/* Generated by the Trail build process. */",
  },
  define: {
    __TRAIL_DIAGNOSTICS_ENABLED__: JSON.stringify(diagnosticsEnabled),
  },
  entryPoints: ["plugin/src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  jsx: "automatic",
  logLevel: "info",
  minify: production,
  outfile: `${outputDirectory}/main.js`,
  sourcemap: oneShot ? false : "inline",
  target: "es2021",
  treeShaking: true,
});

if (oneShot) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
}

await context.watch();

const staticWatchers = staticFiles.map((file) =>
  watch(file, async () => {
    try {
      await copyStaticFiles();
      console.log(`[trail] Updated ${file}`);
    } catch (error) {
      console.error(`[trail] Failed to update ${file}`, error);
    }
  }),
);

async function shutdown() {
  for (const watcher of staticWatchers) {
    watcher.close();
  }

  await context.dispose();
  process.exit(0);
}

process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);

console.log(`[trail] Watching plugin files in ${outputDirectory}`);