import esbuild from "esbuild";
import { watch } from "node:fs";
import { builtinModules } from "node:module";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import process from "node:process";

const mode = process.argv[2] ?? "development";
const production = mode === "production";
const diagnosticsBuild = mode === "diagnostics";
const oneShot = production || diagnosticsBuild;
const diagnosticsEnabled = !production;
const outputDirectory = ".obsidian/plugins/trail";
const staticFiles = ["manifest.json"];
const stylesheetSources = [
  "plugin/styles/tokens.css",
  "plugin/styles/obsidian-variables.css",
  "plugin/styles/obsidian-native.css",
  "plugin/styles/primitives.css",
  "plugin/styles/patterns.css",
  "plugin/styles/entities.css",
  "plugin/styles/pages.css",
  "plugin/styles/shell.css",
  "plugin/styles/foundation.css",
];

async function copyStaticFiles() {
  await mkdir(outputDirectory, { recursive: true });

  await Promise.all(
    staticFiles.map((file) =>
      copyFile(file, `${outputDirectory}/${file}`),
    ),
  );
}

async function buildStylesheet() {
  await mkdir(outputDirectory, { recursive: true });

  const sources = await Promise.all(
    stylesheetSources.map((file) => readFile(file, "utf8")),
  );

  await writeFile(`${outputDirectory}/styles.css`, sources.join("\n"), "utf8");
}

await Promise.all([copyStaticFiles(), buildStylesheet()]);

const context = await esbuild.context({
  banner: {
    js: "/* Generated by the Trail build process. */",
  },
  define: {
    __TRAIL_DIAGNOSTICS_ENABLED__: JSON.stringify(diagnosticsEnabled),
  },
  entryPoints: ["plugin/src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  jsx: "automatic",
  logLevel: "info",
  minify: production,
  outfile: `${outputDirectory}/main.js`,
  sourcemap: oneShot ? false : "inline",
  target: "es2021",
  treeShaking: true,
});

if (oneShot) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
}

await context.watch();

const staticWatchers = staticFiles.map((file) =>
  watch(file, async () => {
    try {
      await copyStaticFiles();
      console.log(`[trail] Updated ${file}`);
    } catch (error) {
      console.error(`[trail] Failed to update ${file}`, error);
    }
  }),
);

let stylesheetBuildQueue = Promise.resolve();

function queueStylesheetBuild(file) {
  stylesheetBuildQueue = stylesheetBuildQueue.then(async () => {
    try {
      await buildStylesheet();
      console.log(`[trail] Updated ${file}`);
    } catch (error) {
      console.error(`[trail] Failed to update ${file}`, error);
    }
  });
}

const stylesheetWatchers = stylesheetSources.map((file) =>
  watch(file, () => {
    queueStylesheetBuild(file);
  }),
);

async function shutdown() {
  for (const watcher of [...staticWatchers, ...stylesheetWatchers]) {
    watcher.close();
  }

  await stylesheetBuildQueue;
  await context.dispose();
  process.exit(0);
}

process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);

console.log(`[trail] Watching plugin files in ${outputDirectory}`);
